# Generated by Django 6.0.5 on 2026-07-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, choices=[('RU', 'Россия'), ('KZ', 'Казахстан'), ('CN', 'Китай'), ('MN', 'Монголия'), ('UA', 'Украина'), ('BY', 'Беларусь'), ('FI', 'Финляндия')], default='RU', max_length=2, null=True),
        ),
    ]
